from trianglesActionSpace import data_convertions
from trianglesActionSpace import display
from trianglesActionSpace import frontend_interface
from trianglesActionSpace import game_logic
from trianglesActionSpace import polygon_creation
from trianglesActionSpace import size_modifications

