# Generated by Django 4.2.16 on 2024-12-21 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField()),
                ('board', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('turns', models.IntegerField()),
                ('triangular_mode', models.BooleanField()),
                ('ai_mode', models.BooleanField()),
                ('ai_starts', models.BooleanField(null=True)),
            ],
        ),
    ]
